name: Shellcheck

on: [ pull_request ]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: -e SC1091 -e SC2034 -e SC2154 -e SC3040
      with:
        scandir: '.'
        additional_files: 'customfiles/sample.depenguin_settings.sh'
        check_together: 'yes'